version: '2'

services:

  blogifier:
      image: neon-registry.b4c5-2917-0fd3-88a5.neoncluster.io/leenet/blogifier:1.11.61
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
