# Inteded for testing and development - look at example.yml for an example.
version: "2.2"
services:
  backup:
    image: neon-registry.b4c5-2917-0fd3-88a5.neoncluster.io/leenet/postgres-backup
    build:
      context: ./
      dockerfile: ./src/Dockerfile
